<div id="dlg-edit" class="easyui-dialog" style="width:340px;height:200px;padding:10px 20px"
    closed="true" modal="true" buttons="#dlg-edit-buttons" title="编辑表单">
    <form id="fm-edit" method="post" action="<?php echo base_url('sjyh/cate/post')?>" novalidate>
        <input type="hidden" name="actionxm" value="">
        <input type="hidden" name="id" value="">
        <table class="fm-table" cellpadding="4px">
            <colgroup>
                <col width="50px" /><col width="*" /><col width="30px" />
            </colgroup>
            <tr>
                <td>名称：</td>
                <td>
                    <input class="easyui-textbox" data-options="required:true, missingMessage:'分类名称不可为空'" style="width:200px;" name="name" value="">
                </td>
                <td>
                    <span style="color:red;">*</span>
                </td>
            </tr>
            <tr>
                <td>图标：</td>
                <td>
                    <input class="easyui-textbox" data-options="required:true, validType:'url', prompt:'输入图标图片的地址',  missingMessage:'图标地址不可为空'" style="width:200px;" name="logo" value="">
                </td>
                <td>
                    <span style="color:red;">*</span>
                </td>
            </tr>
            <tr>
                <td>排序：</td>
                <td>
                    <input class="easyui-numberbox" data-options="prompt:'数字越大越靠前。不填为默认100'" style="width:200px;" name="rank" value="">
                </td>
                <td>
                    <span style="color:red;"></span>
                </td>
            </tr>
        </table>
    </form>
</div>
<div id="dlg-edit-buttons">
    <button class="easyui-linkbutton w90" iconCls="icon-ok" onclick="do_save()">确定</button>
    <button class="easyui-linkbutton w90" iconCls="icon-cancel" onclick="javascript:$('#dlg-edit').dialog('close')">取消</button>
</div>
