<!DOCTYPE html>
<html>
<head>
    <?php
        $this->load->view('/public/linker',array(
            'css'=>array(),
            'js' =>array(),
        ));
        $ctrl_url = base_url('sjyh/zone');
    ?>
</head>
<body>
    <div id="p-dg" class="easyui-panel" title="地区设置" fit="true" border="false">
        <table id="dg" class="easyui-datagrid" title=""
               fit="true" border="false" plain="true"
               toolbar="#toolbar" multiSort="true"
               rownumbers="false" pagination="true" pageList="[50,100,150,200]" pageSize="50"
               singleSelect="true" remote>
            <thead>
                <tr>
                    <th data-options="sortable:true,field:'id',width:50">编号</th>
                    <th data-options="sortable:true,field:'name',width:80">地区名称</th>
                    <th data-options="sortable:true,field:'rank',width:130">排序（值越大越靠前）</th>
                    <th data-options="sortable:true,field:'create_user_name',width:80">创建人</th>
                    <th data-options="sortable:true,field:'create_time',width:130">创建时间</th>
                    <th data-options="sortable:true,field:'update_user_name',width:80">更新人</th>
                    <th data-options="sortable:true,field:'update_time',width:130">更新时间</th>
                </tr>
            </thead>
        </table>

        <div id="toolbar" style="padding:2px 3px;">
            <form id="fm-search" method="post" novalidate>
                <div style="margin:3px 0;">
                    <a class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="open_insert()">添加</a>
                    <a class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="open_update()">修改</a>
                    <a class="easyui-linkbutton" iconCls="icon-cancel" plain="true" onclick="do_delete()">删除</a>
                </div>
            </form>
        </div>
    </div>

    <?php $this->load->view('sjyh/zone_edit');?>

    <script type="text/javascript">
    $(function() {
        window.setTimeout(function() {
            var obj = new Object();
            obj.actionxm = 'search';
            obj.rs = $('#fm-search').form('getData');
            $('#dg').datagrid({
                url: "<?php echo $ctrl_url.'/get'?>",
                method: 'post',
                queryParams: obj
            });
        }, 100);
    });

    function open_insert() {
        $('#fm-edit').form('clear').form('load',{actionxm:'insert'});
        $('#dlg-edit').dialog('setTitle','地区添加').dialog('open');
    }

    function open_update() {
        var info = $('#dg').datagrid('getSelected');
        if(info==null){
            $.messager.alert('操作提示','请选择需要编辑的记录!','warning');
            return;
        }
        var fm_data = {
            actionxm: 'update',
            id: info.id,
            name: info.name,
            rank: info.rank
        };
        console.log(fm_data);
        $('#fm-edit').form('load', fm_data);
        $('#dlg-edit').dialog('setTitle', '地区编辑').dialog('open');
    }

    // 搜索操作
    function do_search() {
        var fm_data = $('#fm-search').form('getData');
        $('#dg').datagrid('options').queryParams = {actionxm:'search', rs:fm_data};
        $('#dg').datagrid('reload');
    }

    function do_save() {
        $('#fm-edit').form('submit', {
            onSubmit: function(){
                return $(this).form('validate');
            },
            success: function(result) {
                var result = eval('('+result+')');
                if (result.success==false){
                    $.messager.alert('操作提示',result.data,'warning');
                } else {
                    $('#dlg-edit').dialog('close');
                    $('#dg').datagrid('reload');
                }
            }
        });
    }

    function format_logo(val, row) {
        var str = '<a href="' + val + '" target="_blank"><img src="' + val + '" style="height:50px;padding-top:5px;"></a>';
        return str;
    }

    function do_delete(){
        var info=$('#dg').datagrid('getSelected');
        if(info==null){
            $.messager.alert('操作提示','请选择需要删除的记录!','warning');
            return;
        }
        $.messager.confirm('操作提示','你确定要删除此记录吗?',function(r){
            if (r){
                $.post('<?php echo $ctrl_url.'/post'; ?>',{id:info.id,actionxm:'delete'},function(result){
                    if (result.success){
                        $('#dg').datagrid('reload');
                    } else {
                        $.messager.alert('操作提示','删除成功');
                    }
                },'json');
            }
        });
    }
    </script>
</body>
</html>

